### ISSUE TITLE
[Code style] Public class members should start with Uppercase letter

### ISSUE THREAD

**Issue by Dmitrii-Naumov** [VarthiniB/AcumaticaNiceLabelIntegration#20]
For instance NLAttributeGraph.assign should probably be Assign.
View att  should be Att (even better if it has a [proper name, e.g. Attributes or LabelAttributes)

**Comment by VarthiniB** [comment]
Changinged naming convention 

https://github.com/VarthiniB/AcumaticaNiceLabelIntegration/pull/31/commits/5c3ec17e4dbb46440cb293d647afb60c7c01b19c
