### ISSUE TITLE
[Code Style] NLLabelAttributes is not a good name for a DAC

### ISSUE THREAD

**Issue by Dmitrii-Naumov** [VarthiniB/AcumaticaNiceLabelIntegration#23]
The better name would be NLLabelAttribute (without S)

**Comment by VarthiniB** [comment]
Changed the name

https://github.com/VarthiniB/AcumaticaNiceLabelIntegration/pull/36/commits/d3904d25824189c4e5581983af652401633df4bd#diff-35ea367f803310e6bf42dd8e3eb59f2e0aad8fb5fdd5e285bca7a11b2fe39147
