### ISSUE TITLE
Strange pattern for selecting rows

### ISSUE THREAD

**Issue by Dmitrii-Naumov** [VarthiniB/AcumaticaNiceLabelIntegration#25]
In SOShipmentEntry_Extension there is the following code:
`NLClassLabelPref lab = new NLClassLabelPref();
 lab = PXSelect<NLClassLabelPref, Where<NLClassLabelPref.customerClassID, Equal<Required<NLClassLabelPref.customerClassID>>>>.Select(Base, Base.customer.Current.CustomerClassID);`

it can be simplified:
`NLClassLabelPref lab = PXSelect<NLClassLabelPref, Where<NLClassLabelPref.customerClassID, Equal<Required<NLClassLabelPref.customerClassID>>>>.Select(Base, Base.customer.Current.CustomerClassID);`

There are couple more places like that in the code

**Comment by VarthiniB** [comment]
Changed the code

https://github.com/VarthiniB/AcumaticaNiceLabelIntegration/pull/32/commits/8c480543429dccf29ba25bd424e1ec06c5f3e6d8
