### ISSUE TITLE
[Certification requirements] SOShipmentEntry_Extension name does not follow our own requirements

### ISSUE THREAD

**Issue by Dmitrii-Naumov** [VarthiniB/AcumaticaNiceLabelIntegration#26]
SOShipmentEntry_Extension is a very generic name for an extension. 
The better name would be 
NLSOShipmentEntry_Extension or something like that.

**Comment by VarthiniB** [comment]
Renamed the file

https://github.com/VarthiniB/AcumaticaNiceLabelIntegration/pull/34/commits/ea4f3a34b6612570f0050946dc01435104db3841
