### ISSUE TITLE
Remove NLClassLabelPref.Subscription key and id 

### ISSUE THREAD

**Issue by Dmitrii-Naumov** [VarthiniB/AcumaticaNiceLabelIntegration#28]
NLClassLabelPref.Subscription key and id  are not in use, please remove.

**Comment by VarthiniB** [comment]
removed the unused fields

https://github.com/VarthiniB/AcumaticaNiceLabelIntegration/pull/33/commits/f97272a68efd3495f2e66f8c507bef4f133e3ac3
