### ISSUE TITLE
NLSubscriptionKey should be a setup DAC

### ISSUE THREAD

**Issue by Dmitrii-Naumov** [VarthiniB/AcumaticaNiceLabelIntegration#29]
1. It does not even need a key

**Comment by Dmitrii-Naumov** [comment]
2. We do not need to select it based on the user who entered it, it should be just 1 record in the DB

**Comment by VarthiniB** [comment]
Changed to setup DAC

[NiceLabelDemo/NiceLabelDemo/DAC/NLSubscriptionKey.cs](https://github.com/VarthiniB/AcumaticaNiceLabelIntegration/pull/36/commits/d3904d25824189c4e5581983af652401633df4bd#diff-e00b2f78f0c8d3c8f5802657b8a6e6795cf74fe6406350cd9841677832233545)


changed the way the subscription key is used

https://github.com/VarthiniB/AcumaticaNiceLabelIntegration/pull/36/commits/d3904d25824189c4e5581983af652401633df4bd#diff-df1f13473817aa20bb69afbdfc1e08bdd78243273087a93c9655cf4815d4a633
