### ISSUE TITLE
PXCacheName should represent user friendly DAC name

### ISSUE THREAD

**Issue by Dmitrii-Naumov** [VarthiniB/AcumaticaNiceLabelIntegration#38]
If you add PXCacheName attribute to DACs, you should use user-friendly name in there.
E.g.   [PXCacheName("NLClassLabelPref")] should probably be   [PXCacheName("NiceLabel Preferences")] or something like that

**Comment by VarthiniB** [comment]
Changed the name

https://github.com/VarthiniB/AcumaticaNiceLabelIntegration/pull/46/commits/80a3b383de1dbe5cbd5276d1e04b32bc384292da#diff-f65c8f8a97bb0700f307890ce16fe6f0d063da60308330a6fa1b6d6371fb8765
