### ISSUE TITLE
If you want a field to be required, please use PXDefaultAttribute for that

### ISSUE THREAD

**Issue by Dmitrii-Naumov** [VarthiniB/AcumaticaNiceLabelIntegration#40]
E.g. NLSubscriptionKey.SubscriptionKey should have PXDefault attribute. 
Setting Required=true in the PXUIField attribute is not enough as it does not provide validation for the field.

**Comment by VarthiniB** [comment]
Added the pxdefault attribute

https://github.com/VarthiniB/AcumaticaNiceLabelIntegration/compare/withSOurceCode?expand=1#diff-4484b6bcde4dce1eb7dbeeb7a3d14dd3217fde8c49b892c66c313224ab574091
