### ISSUE TITLE
NLSyncPref.Description is not declared properly

### ISSUE THREAD

**Issue by Dmitrii-Naumov** [VarthiniB/AcumaticaNiceLabelIntegration#41]
- NLSyncPref.Description should have PXUIField Attribute
- NLSyncPref.Description should have correcsponding abstract class

**Comment by VarthiniB** [comment]
Added  the description field in the format

https://github.com/VarthiniB/AcumaticaNiceLabelIntegration/compare/withSOurceCode?expand=1#diff-a9a5a2ca433b4d008df7a3dd990fb4552a124d941e0aa0ac41793874d830f66d
