### ISSUE TITLE
NLSyncPref DAC should not be used for reports and GIs

### ISSUE THREAD

**Issue by Dmitrii-Naumov** [VarthiniB/AcumaticaNiceLabelIntegration#42]
NLSyncPref has PXCacheName attribute which makes it visible for selection in GIs and Reports. However, there is not point in using that DAC in GIs or reports. 
Please remove the PXCacheName attribute and replace it with PXHidden attribute

**Comment by VarthiniB** [comment]
Removed PXCAcheName and changed it to PXHidden

https://github.com/VarthiniB/AcumaticaNiceLabelIntegration/compare/withSOurceCode?expand=1#diff-a9a5a2ca433b4d008df7a3dd990fb4552a124d941e0aa0ac41793874d830f66d
