### ISSUE TITLE
Helper class NLWebCalls should be static

### ISSUE THREAD

**Issue by Dmitrii-Naumov** [VarthiniB/AcumaticaNiceLabelIntegration#43]
It's a best practice to mark a class with static attribute if it only contains static methods and nothing else

**Comment by VarthiniB** [comment]
Made the helper class static

https://github.com/VarthiniB/AcumaticaNiceLabelIntegration/compare/withSOurceCode?expand=1#diff-43da226db635d144cc2d5f8c5327ccb139c17d15de599dff7a4c7acf8180bd13
