### ISSUE TITLE
There are three graph that handle Subscription key

### ISSUE THREAD

**Issue by Dmitrii-Naumov** [VarthiniB/AcumaticaNiceLabelIntegration#45]
There are the following graphs:

- NLPrefMaint
- NLSetupMaint 
- NLSubKeyMaint 

It seems only one of them is required. Please remove the other two

**Comment by VarthiniB** [comment]
Removed NLSUbKeyMaint graph

NLSetupMaint is the graph for the setup screen

NLPrefMaint is the graph for the screen linking Print, customerclass and Label.

have added the Setup related details in the constructor, to have the screen redirected, if the subscription key is not added.

**Comment by VarthiniB** [comment]
https://github.com/VarthiniB/AcumaticaNiceLabelIntegration/compare/withSOurceCode?expand=1#diff-bd2ad88a2ef41c02184dd5b7883b4793b3ac2aae65b8c045f7332e35d8b973f7
