### ISSUE TITLE
NLWebCalls methods structure

### ISSUE THREAD

**Issue by Dmitrii-Naumov** [VarthiniB/AcumaticaNiceLabelIntegration#47]
NLWebCalls is a helper class and it should incorporate the logic required for it to work. 
Methods in that class should have a simple and obvious signature with clear purpose and expected value of each input parameter and return values.

Currently that's not the case, e.g. CreateRequestFromShipment has `string add` parameter. It's not clear what the expected value and expected structure of the value is. 
Also all methods in the class have URL parameter. It's not clear what URL should be passed from outside and why it's required. From my point of view the URL is the property of the methods inside NLWebCalls  class, thus the URL should be a constant inside the methods instead of a parameter.

**Comment by Dmitrii-Naumov** [comment]
As for the return parameters of the methods, it should be clear what the result is. 
For CreateRequestFromShipment I suggest to use either bool return value that represents if the API call was successful or have methods as void and throw an exception if the API call was not successful.

**Comment by VarthiniB** [comment]
Changed the return type:
https://github.com/VarthiniB/AcumaticaNiceLabelIntegration/pull/58/commits/4177f61e4f2069e9586ca655c358e69e12b82cb3

made the url constant:
https://github.com/VarthiniB/AcumaticaNiceLabelIntegration/pull/59/commits/51d0f576e4e3071036d88d72c8fbcf5931e07bc6
