### ISSUE TITLE
Showing message to a user in PrintNiceLabel

### ISSUE THREAD

**Issue by Dmitrii-Naumov** [VarthiniB/AcumaticaNiceLabelIntegration#48]
Currently when a PrintNiceLabel action completes, there is an exception being thrown that indicates that the label was sent to the Nicelabel
Throwing exceptions in that case is not the best practice. 
I suggest to wrap the method that performs API call in LongRun which give the following benefits:
1. Shows nice green checkmark to the user when completes successfully and shows nice red cross when fails.
2. Allows to avoid freezing of the UI if the API call takes more time than expected

**Comment by VarthiniB** [comment]
fixed the response viewing using pxlongoperation 

https://github.com/VarthiniB/AcumaticaNiceLabelIntegration/pull/57/commits/48924f3929364dfa9387fed33fc64ac8178d442f#diff-b311e93d4ce325245e0b0ce46003faea5bb12176751492c3b159cf263ae1bd98
