### ISSUE TITLE
NLSyncProcess public string Subkey;

### ISSUE THREAD

**Issue by Dmitrii-Naumov** [VarthiniB/AcumaticaNiceLabelIntegration#50]
There is public string Subkey in the NLSyncProcess graph. It has no purpose, please remove

**Comment by VarthiniB** [comment]
Removed the unused variable

https://github.com/VarthiniB/AcumaticaNiceLabelIntegration/pull/56/commits/652b9e5acad3278eb43583ac11f99e19efe7e2fa
