### ISSUE TITLE
NLSubscriptionKey key fields

### ISSUE THREAD

**Issue by Dmitrii-Naumov** [VarthiniB/AcumaticaNiceLabelIntegration#51]
We would like to only have a single NLSubscriptionKey and we want it to be a setup DAC.
In that case it does not need the ID/identity field. Please remove it

**Comment by VarthiniB** [comment]
removed the Keyid field

https://github.com/VarthiniB/AcumaticaNiceLabelIntegration/pull/55/commits/f5f30661e9db7f89bcbb64be3bfa83868d8609ab
