### ISSUE TITLE
PXCacheName attribute should represent user friendly DAC name

### ISSUE THREAD

**Issue by Dmitrii-Naumov** [VarthiniB/AcumaticaNiceLabelIntegration#52]
For instance on NLSubscriptionKey there is  `[PXCacheName("NiceLabel Add Subscription Key")]` attribute
It's not a good DAC name because it has add verb. It's misleading because the DAC is just the data class and not an action thus it should not have verbs in the name

**Comment by VarthiniB** [comment]
Chnaged the PXCache name 

https://github.com/VarthiniB/AcumaticaNiceLabelIntegration/pull/55/commits/f5f30661e9db7f89bcbb64be3bfa83868d8609ab
