### ISSUE TITLE
Since subscription key does not have key field in the DAC now it does not need the PK

### ISSUE THREAD

**Issue by Dmitrii-Naumov** [VarthiniB/AcumaticaNiceLabelIntegration#63]
Please remove `  public class PK : PrimaryKeyOf<NLSubscriptionKey>.By<subscriptionKey>`
from Subscription key DAC

**Comment by VarthiniB** [comment]
Removed the primarykey related section 

https://github.com/VarthiniB/AcumaticaNiceLabelIntegration/pull/65
