### ISSUE TITLE
Sql_NLSubscriptionKey.xml still has Subscription ley as a part of the key

### ISSUE THREAD

**Issue by Dmitrii-Naumov** [VarthiniB/AcumaticaNiceLabelIntegration#66]
Please leave only CompanyID as a DB key for the table

**Comment by VarthiniB** [comment]
Removed the column from the primary key

https://github.com/VarthiniB/AcumaticaNiceLabelIntegration/pull/67/commits/74d68fdae0fec6e5c52bb354ec33b7356f5cb955
